import { tenureFloorStage } from "./status";

/**
 * Persistent Spross "identity" — schema-versioned, stored in one localStorage key and guarded
 * exactly like pp:lastSeen (localStorage throws in private mode / may be evicted). Only the
 * IDENTITY (stage/peak/skins/milestones) lives here and only ever ratchets UP; the live MOOD is
 * never persisted (it's a transient mirror computed each render).
 */
export interface SprossStore {
  v: number;
  peakVitality: number; // 0..100, max-ratcheted — drives the (monotonic) growth bar in P1
  stageMax: number; // 1..6, RESOLVED stage, max-ratcheted (never recomputed downward)
  stageSeen: number; // highest stage the level-up bloom has played for (one-shot gate)
  milestones: Record<string, string>; // P1: id -> YYYY-MM-DD first reached (append-only)
  skins: string[]; // P1: unlocked skin ids
  activeSkin: string | null; // P1
  petCount: number; // P2
  vacation: { on: boolean; since: string | null }; // P2
}

const KEY = "pp:spross";

export function defaultSprossStore(): SprossStore {
  return {
    v: 1,
    peakVitality: 0,
    stageMax: 1,
    stageSeen: 1,
    milestones: {},
    skins: [],
    activeSkin: null,
    petCount: 0,
    vacation: { on: false, since: null },
  };
}

/** Load + validate. Returns null if absent/corrupt/older-schema (caller treats null as first hydrate).
 *  Drops an unknown / not-yet-unlocked activeSkin (allow-list, like theme.tsx's background validation). */
export function loadSprossStore(): SprossStore | null {
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Partial<SprossStore>;
    if (!parsed || parsed.v !== 1) return null;
    const store = { ...defaultSprossStore(), ...parsed };
    if (
      store.activeSkin &&
      !(SKIN_IDS.has(store.activeSkin) && store.skins.includes(store.activeSkin))
    ) {
      store.activeSkin = null;
    }
    return store;
  } catch {
    return null;
  }
}

export function saveSprossStore(store: SprossStore): void {
  try {
    localStorage.setItem(KEY, JSON.stringify(store));
  } catch {
    /* localStorage unavailable (private mode) — progression is best-effort, never blocks the UI */
  }
}

/**
 * Ratchet the identity upward only and decide whether a level-up bloom should play.
 *
 * `serverStageMax`/`serverPeak` are the DURABLE high-water-mark from the user row (GET /api/stats):
 * they are the real never-downgrade floor that survives storage eviction / a new device / private
 * mode — localStorage alone cannot promise that. `needsServerSync` is true when the local/live max
 * has climbed past the server, so the caller PATCHes the server (which also max()es).
 *
 * `storeExisted` MUST be the mount-time truth (read once BEFORE any write): the two queries (plants,
 * stats) resolve on different renders, so re-reading the key inside the effect would see the record
 * the effect itself just wrote and fire a fake first-open bloom. Gating bloom on the mount-time flag
 * makes a fresh device land on its real (server-restored) stage silently. The tenure floor is a
 * secondary fallback for the rare case where the server value is unavailable too.
 */
export function ratchetSpross(
  prev: SprossStore | null,
  liveVitality: number,
  liveStage: number,
  oldestAgeDays: number,
  storeExisted: boolean,
  serverStageMax = 1,
  serverPeak = 0,
): { store: SprossStore; bloom: boolean; needsServerSync: boolean } {
  const base = prev ?? defaultSprossStore();
  const seedFloor = storeExisted ? 1 : tenureFloorStage(oldestAgeDays);
  const stageMax = Math.max(base.stageMax, liveStage, seedFloor, serverStageMax);
  const peakVitality = Math.max(base.peakVitality, liveVitality, serverPeak);
  const bloom = storeExisted && stageMax > base.stageSeen;
  const needsServerSync = stageMax > serverStageMax || peakVitality > serverPeak;
  return {
    store: { ...base, peakVitality, stageMax, stageSeen: stageMax },
    bloom,
    needsServerSync,
  };
}

// --- Milestones (P1.3) + Skins (P1.4): deterministic, permanent, never purchasable/expiring. ---

/** A cosmetic skin = a PRE-BAKED per-character recolor (pot/cheeks/eyes/gold stay terracotta/etc.),
 *  0 new art — generated by scripts/build_sprites.py as spross-stage{N}-{id}.png. The frontend just
 *  swaps the sprite URL by id; unlocked permanently once ANY `via` milestone is reached. The recolor
 *  hue (deg) lives in the build script's SKIN_RECOLOR, keyed by the SAME id. */
export interface SkinDef {
  id: string;
  via: string[];
}
export const SKINS: SkinDef[] = [
  { id: "tau", via: ["stufe_3"] }, // teal
  { id: "mondlicht", via: ["streak_30"] }, // blue
  { id: "amethyst", via: ["stufe_5"] }, // violet
  { id: "beere", via: ["konsistenz_80"] }, // magenta
  { id: "koralle", via: ["pflege_100"] }, // coral/red
];
const SKIN_IDS = new Set(SKINS.map((s) => s.id));

/** Inputs for milestone detection — all from the existing ['stats'] query + the session greeting. */
export interface ProgressCtx {
  stageMax: number;
  consistencyPct: number;
  streakDays: number;
  thirstyCount: number;
  totalPlants: number;
  petCount: number;
  greeting: boolean;
}

/** Milestone gates — only from data we already have. NO lifetime counts ("50 waterings" => v3 backend). */
export const MILESTONES: { id: string; reached: (c: ProgressCtx) => boolean }[] = [
  { id: "stufe_3", reached: (c) => c.stageMax >= 3 },
  { id: "stufe_5", reached: (c) => c.stageMax >= 5 },
  { id: "stufe_6", reached: (c) => c.stageMax >= 6 },
  { id: "konsistenz_80", reached: (c) => c.consistencyPct >= 80 },
  { id: "streak_7", reached: (c) => c.streakDays >= 7 },
  { id: "streak_30", reached: (c) => c.streakDays >= 30 },
  { id: "alle_versorgt", reached: (c) => c.totalPlants >= 3 && c.thirstyCount === 0 },
  { id: "wiederkehr", reached: (c) => c.greeting },
  { id: "pflege_100", reached: (c) => c.petCount >= 100 },
];

export function unlockedSkins(milestones: Record<string, string>): string[] {
  return SKINS.filter((s) => s.via.some((m) => m in milestones)).map((s) => s.id);
}

/**
 * Append newly-reached milestones (dated, never removed) and recompute unlocked skins. Pure.
 * `storeExisted` gates DATING: on a fresh device that restored a high stage from the server, the
 * already-true milestones are seeded with an EMPTY date (unknown) rather than a fabricated "today".
 */
export function evaluateProgress(
  prev: SprossStore,
  ctx: ProgressCtx,
  storeExisted: boolean,
  today: string,
): SprossStore {
  const milestones = { ...prev.milestones };
  for (const m of MILESTONES) {
    if (m.reached(ctx) && !(m.id in milestones)) {
      milestones[m.id] = storeExisted ? today : "";
    }
  }
  const skins = Array.from(new Set([...prev.skins, ...unlockedSkins(milestones)]));
  return { ...prev, milestones, skins };
}
